export const FETCH_COMIC_LIST_PENDING = 'FETCH_COMIC_LIST_PENDING'
export const FETCH_COMIC_LIST_SUCCESS = 'FETCH_COMIC_LIST_SUCCESS'
export const FETCH_COMIC_LIST_ERROR = 'FETCH_COMIC_LIST_ERROR'

export const FETCH_POPULAR_LIST_PENDING = 'FETCH_POPULAR_LIST_PENDING'
export const FETCH_POPULAR_LIST_SUCCESS = 'FETCH_POPULAR_LIST_SUCCESS'
export const FETCH_POPULAR_LIST_ERROR = 'FETCH_POPULAR_LIST_ERROR'

export const FETCH_EPOSIDE_LIST_PENDING = 'FETCH_EPOSIDE_LIST_PENDING'
export const FETCH_EPOSIDE_LIST_SUCCESS = 'FETCH_EPOSIDE_LIST_SUCCESS'
export const FETCH_EPOSIDE_LIST_ERROR = 'FETCH_EPOSIDE_LIST_ERROR'

export const SET_CURRENT_MANGA = "SET_CURRENT_MANGA"
export const SHOW_APPBAR = "SHOW_APPBAR"
export const HIDE_APPBAR = "HIDE_APPBAR"

export const FETCH_PICTURE_LIST_PENDING = 'FETCH_PICTURE_LIST_PENDING'
export const FETCH_PICTURE_LIST_SUCCESS = 'FETCH_PICTURE_LIST_SUCCESS'
export const FETCH_PICTURE_LIST_ERROR = 'FETCH_PICTURE_LIST_ERROR'

